# Generated by Django 4.1 on 2022-08-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='day',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='task',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
