# Generated by Django 4.1 on 2022-08-08 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_material_cost_material_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='materials',
            field=models.ManyToManyField(to='main_app.material'),
        ),
    ]
