# Generated by Django 4.1 on 2022-08-08 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_item_materials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='cost',
        ),
    ]
