# Generated by Django 4.1 on 2022-08-08 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_remove_material_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='cost',
            field=models.IntegerField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
